services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.9
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka
  kafka:
    image: confluentinc/cp-kafka:7.0.9
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    links:
      - kafka
      - zookeeper
    networks:
      - kafka

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: stahl-db
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD?:err}
      POSTGRES_USER: stahl-user
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./deploy/config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "./deploy/data/prometheus:/prometheus"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana-enterprise:latest
    environment:
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: secret
    ports:
      - "3000:3000"
    volumes:
      - "./deploy/config/grafana/provisioning:/etc/grafana/provisioning"
      - "./deploy/data/grafana:/var/lib/grafana"
    networks:
      - monitoring
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - monitoring

  stahl-eureka-server:
    restart: always
    build:
      dockerfile:  Dockerfile-JVM
      args:
        JAR_FILE: stahl-eureka/build/libs/stahl-eureka.jar
    environment:
      LOKI: http://host.docker.internal:3100
    networks:
      - stahl-net
    ports:
      - "8761:8761"

  stahl-gateway-server:
    restart: always
    build:
      dockerfile:  Dockerfile-JVM
      args:
        JAR_FILE: stahl-gateway/build/libs/stahl-gateway.jar
    environment:
      LOKI: http://host.docker.internal:3100
    networks:
      - stahl-net
    ports:
      - "8080:8080"

  stahl-config-server:
    restart: always
    build:
      dockerfile:  Dockerfile-JVM
      args:
        JAR_FILE: stahl-config/build/libs/stahl-config.jar
    environment:
      SPRING_PROFILES_ACTIVE: git
      LOKI: http://host.docker.internal:3100
    networks:
      - stahl-net
    ports:
      - "8888:8888"

  stahl-admin-server:
    build:
      dockerfile:  Dockerfile-JVM
      args:
        JAR_FILE: stahl-admin/build/libs/stahl-admin.jar
    environment:
      LOKI: http://host.docker.internal:3100
    networks:
      - stahl-net
    ports:
      - "9999:9999"
  stahl-users-service:
    depends_on:
      stahl-eureka-server:
        restart: true
        condition: service_healthy
      stahl-config-server:
        restart: true
        condition: service_healthy
    build:
      dockerfile: Dockerfile-JVM
      args:
        JAR_FILE: stahl-users/build/libs/stahl-users.jar
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      LOKI: http://host.docker.internal:3100
    ports:
      - "8081:8081"
  # bots
  nivora-bot:
    depends_on:
      stahl-eureka-server:
        restart: true
        condition: service_healthy
      stahl-config-server:
        restart: true
        condition: service_healthy
    build:
      dockerfile: Dockerfile-JVM
      args:
        JAR_FILE: stahl-bots/nivora/build/libs/nivora.jar
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      LOKI: http://host.docker.internal:3100
    networks:
      - stahl-net
    ports:
      - "7072:7072"
  serafim-bot:
    depends_on:
      stahl-eureka-server:
        restart: true
        condition: service_healthy
      stahl-config-server:
        restart: true
        condition: service_healthy
    build:
      dockerfile: Dockerfile-JVM
      args:
        JAR_FILE: stahl-bots/serafim/build/libs/serafim.jar
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      LOKI: http://host.docker.internal:3100
    networks:
      - stahl-net
    ports:
      - "7071:7071"
  zentra-bot:
    depends_on:
      stahl-eureka-server:
        restart: true
        condition: service_healthy
      stahl-config-server:
        restart: true
        condition: service_healthy
    build:
      dockerfile: Dockerfile-JVM
      args:
        JAR_FILE: stahl-bots/zentra/build/libs/zentra.jar
    environment:
      LOKI: http://host.docker.internal:3100
    networks:
      - stahl-net
    ports:
      - "7070:7070"

networks:
  kafka:
    driver: bridge
  monitoring:
    driver: bridge
  stahl-net:
    driver: bridge
